name: Validate appstream metadata xml
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths:
      - packaging/app.comaps.desktop.metainfo.xml
      - .forgejo/workflows/appstream-check.yaml  # Run check on self change

jobs:
  validate-appstream:
    name: Validate appstream metadata xml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: https://github.com/actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            packaging/app.comaps.desktop.metainfo.xml

      - name: Install appstream validator and flatpak Builder
        shell: bash
        run: |
          apt update -y
          apt install -y \
              flatpak
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y org.flatpak.Builder

      - name: Lint appstream data with flatpak Builder
        shell: bash
        run: flatpak run --command=flatpak-builder-lint org.flatpak.Builder appstream packaging/app.comaps.desktop.metainfo.xml

      - name: Run appstreamcli in pedantic mode
        shell: bash
        run: flatpak run --command=appstreamcli org.flatpak.Builder validate --pedantic packaging/app.comaps.desktop.metainfo.xml
